### ISSUE TITLE
Breaks 'Drug Policies' system?

### ISSUE THREAD

**Issue by DarthLuca** [emipa606/YayosCombat3#4]
Not sure if it is a clash, but this mod seems to break the 'Drug policies' system. With this mod installed when I go to 'Drug Policies' and then try to select a policy it shows NO list of drugs.

**Comment by emipa606** [comment]
Does this happen with only this mod loaded?

**Comment by DarthLuca** [comment]
I will try... Ok, With just Harmony, Hugslib, and this mod, yes it still happens!
.
Running Rimworld V.1.4.3524. Harmony Lib 2.2.2.0, Mod 1.5.0.0

**Comment by emipa606** [comment]
Does not happen in my tests
You are running an outdated version of the game however, the current version is `1.4.3901 rev238`

**Comment by DarthLuca** [comment]
I will see if I can update to latest version. Thx.
.
You will be pleased to hear that moving to version 1.4.3901 seems to have fixed the issue. Thx again.
