### ISSUE TITLE
can't shoot with ranged weapons

### ISSUE THREAD

**Issue by howozz** [emipa606/YayosCombat3#7]
when my pawns try to shoot, they just freeze aiming
and i get this spammed on my console https://gist.github.com/HugsLibRecordKeeper/b3695b17dc8160cdc5c6484d3922b785#file-output_log-txt-L4482

**Comment by emipa606** [comment]
Can you replicate it with only this mod loaded? With that amount of mods there is a lot of possible causes.

**Comment by howozz** [comment]
new logs with minimal mod list: https://gist.github.com/HugsLibRecordKeeper/1d3ae316f3e4b2ff113bfab366f80a7c

**Comment by emipa606** [comment]
What weapon is it that you have issue with?

**Comment by howozz** [comment]
i didn't test all the weapons but so far sniper, charge rifle, revolver and bow cause this issue btw im running the linux version of the game could that be the issue maybe?

**Comment by emipa606** [comment]
Just tested the mod and got no issue, what mod-settings do you use?

**Comment by howozz** [comment]
![2024-05-15_23-49-32](https://github.com/emipa606/YayosCombat3/assets/107792562/664d8d35-e20d-4035-9010-d02a3ce8d7dc)
![2024-05-15_23-49-37](https://github.com/emipa606/YayosCombat3/assets/107792562/51c987a7-880e-42b1-9cf8-2f6e39780684)

**Comment by emipa606** [comment]
Tested those settings with no issues either.

Just noticed your rimworld version in the log RimWorld 1.5.4035
That version is over 2 months old, the current version is 1.5.4085.
Can you update your game and test again?

**Comment by howozz** [comment]
i just updated and it's working fine now
sorry for taking your time
