### ISSUE TITLE
Incorrect armor effectivness setting calculation.

### ISSUE THREAD

**Issue by Gensando** [emipa606/YayosCombat3#8]
I am not 100% sure, but I think it takes into account accuracy effectiveness from settings instead of armor effectiveness for armor algorithm calculations. Not sure if it's intended or not.

https://github.com/emipa606/YayosCombat3/blob/10876d79bb4b0be24701cc8577da53ca1950f133/Source/yayoCombat/yayoCombat/yayoCombat.cs#L305

**Comment by emipa606** [comment]
Nice catch, added in 
2ebd4d5
