### ISSUE TITLE
Incompatible with [RH2] Rimmu-Nation² - Security 's new rocket turret

### ISSUE THREAD

**Issue by Ezigunev** [emipa606/YayosCombat3#9]
The new rocket turret added by the mod [RH2] Rimmu-Nation² - Security is incompatible with yayo's combat 3 as was stated in the mod comments section by Chicken Plucker:

"YAYO's COMBAT does this for other mods that add rockets, unless its pre-patched (no idea how to do that, much like CE patches). I'm not the one to ask if I can fix it, because my mod does not mess with the mechanics and physics of vanilla, YC does. If anything, I'd ask YAYO to sort it out, he's been probably told this for ages but I don't know how busy the gentleman is. Sadly my only suggestion is disable it, but I understand that's not a decision some would find easy to make"

I hope you could look at this in your spare time (that you probably don't have with so much mods to work on). 
Thanks for your hard work :*

**Comment by emipa606** [comment]
Could you perhaps describe what the incompatibility is?

**Comment by emipa606** [comment]
Please comment again if you find out what the incompatibility is.
